kind = "web"
previewPath = "/"
title = "Fibranusa"
version = "1.0.0"
id = "artifacts/fibranusa"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19616

[services.development]
run = "pnpm --filter @workspace/fibranusa run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/fibranusa", "run", "build" ]
publicDir = "artifacts/fibranusa/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19616"
BASE_PATH = "/"
